{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "baf14a98-6c47-4b3f-aa76-3d0ec025d226",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found: 8\n",
      "Scraping 1/8\n",
      "Scraping 2/8\n",
      "Scraping 3/8\n",
      "Scraping 4/8\n",
      "Scraping 5/8\n",
      "Scraping 6/8\n",
      "Scraping 7/8\n",
      "Scraping 8/8\n",
      "Dataset created successfully!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "\n",
    "BASE_URL = \"https://insideairbnb.com/get-the-data/\"\n",
    "\n",
    "headers = {\"User-Agent\": \"Mozilla/5.0\"}\n",
    "\n",
    "def get_csv_links():\n",
    "    r = requests.get(BASE_URL, headers=headers)\n",
    "    soup = BeautifulSoup(r.text, \"html.parser\")\n",
    "\n",
    "    links = []\n",
    "    for a in soup.find_all(\"a\"):\n",
    "        href = a.get(\"href\")\n",
    "        if href and \"listings.csv\" in href:\n",
    "            links.append(href)\n",
    "\n",
    "    return links[:8]  # limit for assignment\n",
    "\n",
    "\n",
    "def load_data(url):\n",
    "    try:\n",
    "        df = pd.read_csv(url)\n",
    "        df[\"source\"] = url\n",
    "        df[\"scraped_at\"] = pd.Timestamp.now()\n",
    "        return df\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "\n",
    "all_dfs = []\n",
    "\n",
    "links = get_csv_links()\n",
    "print(\"Found:\", len(links))\n",
    "\n",
    "for i, link in enumerate(links):\n",
    "    print(f\"Scraping {i+1}/{len(links)}\")\n",
    "\n",
    "    df = load_data(link)\n",
    "    if df is not None:\n",
    "        all_dfs.append(df)\n",
    "\n",
    "    time.sleep(2)\n",
    "\n",
    "final_df = pd.concat(all_dfs, ignore_index=True)\n",
    "final_df.to_csv(\"data_raw.csv\", index=False)\n",
    "\n",
    "print(\"Dataset created successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "72b3b0f2-325f-4262-a193-ecc52e98bd88",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\470302027.py:4: DtypeWarning: Columns (12,34,78) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  df = pd.read_csv(\"data_raw.csv\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Preprocessing complete\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "df = pd.read_csv(\"data_raw.csv\")\n",
    "\n",
    "# -----------------------\n",
    "# CLEANING\n",
    "# -----------------------\n",
    "df = df.dropna(subset=[\"price\", \"number_of_reviews\"])\n",
    "\n",
    "df[\"price\"] = df[\"price\"].replace('[\\$,]', '', regex=True).astype(float)\n",
    "\n",
    "# -----------------------\n",
    "# TARGET VARIABLE\n",
    "# -----------------------\n",
    "median_reviews = df[\"number_of_reviews\"].median()\n",
    "df[\"popular\"] = (df[\"number_of_reviews\"] > median_reviews).astype(int)\n",
    "\n",
    "# -----------------------\n",
    "# FEATURE ENGINEERING\n",
    "# -----------------------\n",
    "df[\"price_per_night\"] = df[\"price\"] / (df[\"minimum_nights\"] + 1)\n",
    "\n",
    "df[\"review_intensity\"] = df[\"number_of_reviews\"] / (df[\"availability_365\"] + 1)\n",
    "\n",
    "df[\"value_score\"] = df[\"number_of_reviews\"] / (df[\"price\"] + 1)\n",
    "\n",
    "df[\"host_activity\"] = df[\"calculated_host_listings_count\"]\n",
    "\n",
    "df[\"location_score\"] = df[\"latitude\"] * df[\"longitude\"]\n",
    "\n",
    "# -----------------------\n",
    "# SAVE CLEAN DATA\n",
    "# -----------------------\n",
    "df.to_csv(\"data_clean.csv\", index=False)\n",
    "\n",
    "print(\"Preprocessing complete\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "441c4be0-e489-4839-97fa-408e08278b50",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\2323670257.py:5: DtypeWarning: Columns (34,78) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  df = pd.read_csv(\"data_clean.csv\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                 id     scrape_id       host_id  host_profile_id  \\\n",
      "count  2.111800e+04  1.055900e+04  2.111800e+04              0.0   \n",
      "mean   6.526402e+17  2.025092e+13  1.746359e+08              NaN   \n",
      "std    5.752266e+17  7.118010e+06  1.953535e+08              NaN   \n",
      "min    2.788600e+04  2.025091e+13  3.592000e+03              NaN   \n",
      "25%    3.580079e+07  2.025091e+13  1.992984e+07              NaN   \n",
      "50%    7.671779e+17  2.025091e+13  8.419797e+07              NaN   \n",
      "75%    1.183904e+18  2.025092e+13  2.801303e+08              NaN   \n",
      "max    1.517509e+18  2.025093e+13  7.194141e+08              NaN   \n",
      "\n",
      "       host_profile_url  hosts_time_as_user_years  hosts_time_as_user_months  \\\n",
      "count               0.0                       0.0                        0.0   \n",
      "mean                NaN                       NaN                        NaN   \n",
      "std                 NaN                       NaN                        NaN   \n",
      "min                 NaN                       NaN                        NaN   \n",
      "25%                 NaN                       NaN                        NaN   \n",
      "50%                 NaN                       NaN                        NaN   \n",
      "75%                 NaN                       NaN                        NaN   \n",
      "max                 NaN                       NaN                        NaN   \n",
      "\n",
      "       hosts_time_as_host_years  hosts_time_as_host_months  \\\n",
      "count                       0.0                        0.0   \n",
      "mean                        NaN                        NaN   \n",
      "std                         NaN                        NaN   \n",
      "min                         NaN                        NaN   \n",
      "25%                         NaN                        NaN   \n",
      "50%                         NaN                        NaN   \n",
      "75%                         NaN                        NaN   \n",
      "max                         NaN                        NaN   \n",
      "\n",
      "       host_listings_count  ...  calculated_host_listings_count_private_rooms  \\\n",
      "count         10554.000000  ...                                  10559.000000   \n",
      "mean             16.383172  ...                                      1.063832   \n",
      "std              98.629107  ...                                      6.091235   \n",
      "min               1.000000  ...                                      0.000000   \n",
      "25%               1.000000  ...                                      0.000000   \n",
      "50%               1.000000  ...                                      0.000000   \n",
      "75%               4.000000  ...                                      0.000000   \n",
      "max            1649.000000  ...                                     70.000000   \n",
      "\n",
      "       calculated_host_listings_count_shared_rooms  reviews_per_month  \\\n",
      "count                                 10559.000000       18822.000000   \n",
      "mean                                      0.027181           1.697232   \n",
      "std                                       0.397139           2.365424   \n",
      "min                                       0.000000           0.010000   \n",
      "25%                                       0.000000           0.380000   \n",
      "50%                                       0.000000           0.920000   \n",
      "75%                                       0.000000           2.400000   \n",
      "max                                       9.000000          99.420000   \n",
      "\n",
      "       neighbourhood_group       popular  price_per_night  review_intensity  \\\n",
      "count                  0.0  21118.000000     21118.000000      21118.000000   \n",
      "mean                   NaN      0.492376       126.741797          1.792517   \n",
      "std                    NaN      0.499954      1159.210658         13.843148   \n",
      "min                    NaN      0.000000         0.094391          0.000000   \n",
      "25%                    NaN      0.000000        33.000000          0.025717   \n",
      "50%                    NaN      0.000000        52.500000          0.160000   \n",
      "75%                    NaN      1.000000        83.500000          0.719013   \n",
      "max                    NaN      1.000000     40009.000000        659.000000   \n",
      "\n",
      "        value_score  host_activity  location_score  \n",
      "count  21118.000000   21118.000000    21118.000000  \n",
      "mean       0.657575       5.986836     -517.254148  \n",
      "std        1.512680      15.501532     1360.828331  \n",
      "min        0.000000       1.000000    -2946.706881  \n",
      "25%        0.017399       1.000000      224.773196  \n",
      "50%        0.092683       1.000000      254.041874  \n",
      "75%        0.565976       3.000000      256.144133  \n",
      "max       38.323308     113.000000      263.540677  \n",
      "\n",
      "[8 rows x 58 columns]\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 21118 entries, 0 to 21117\n",
      "Data columns (total 93 columns):\n",
      " #   Column                                        Non-Null Count  Dtype  \n",
      "---  ------                                        --------------  -----  \n",
      " 0   id                                            21118 non-null  int64  \n",
      " 1   listing_url                                   10559 non-null  object \n",
      " 2   scrape_id                                     10559 non-null  float64\n",
      " 3   last_scraped                                  10559 non-null  object \n",
      " 4   source                                        21118 non-null  object \n",
      " 5   name                                          21118 non-null  object \n",
      " 6   description                                   10260 non-null  object \n",
      " 7   neighborhood_overview                         5476 non-null   object \n",
      " 8   picture_url                                   10559 non-null  object \n",
      " 9   host_id                                       21118 non-null  int64  \n",
      " 10  host_url                                      10559 non-null  object \n",
      " 11  host_profile_id                               0 non-null      float64\n",
      " 12  host_profile_url                              0 non-null      float64\n",
      " 13  host_name                                     21108 non-null  object \n",
      " 14  host_since                                    10554 non-null  object \n",
      " 15  hosts_time_as_user_years                      0 non-null      float64\n",
      " 16  hosts_time_as_user_months                     0 non-null      float64\n",
      " 17  hosts_time_as_host_years                      0 non-null      float64\n",
      " 18  hosts_time_as_host_months                     0 non-null      float64\n",
      " 19  host_location                                 8929 non-null   object \n",
      " 20  host_about                                    5686 non-null   object \n",
      " 21  host_response_time                            9333 non-null   object \n",
      " 22  host_response_rate                            9333 non-null   object \n",
      " 23  host_acceptance_rate                          9927 non-null   object \n",
      " 24  host_is_superhost                             10388 non-null  object \n",
      " 25  host_thumbnail_url                            10554 non-null  object \n",
      " 26  host_picture_url                              10554 non-null  object \n",
      " 27  host_neighbourhood                            2482 non-null   object \n",
      " 28  host_listings_count                           10554 non-null  float64\n",
      " 29  host_total_listings_count                     10554 non-null  float64\n",
      " 30  host_verifications                            10554 non-null  object \n",
      " 31  host_has_profile_pic                          10554 non-null  object \n",
      " 32  host_identity_verified                        10554 non-null  object \n",
      " 33  neighbourhood                                 16035 non-null  object \n",
      " 34  neighbourhood_cleansed                        10559 non-null  object \n",
      " 35  neighbourhood_group_cleansed                  0 non-null      float64\n",
      " 36  latitude                                      21118 non-null  float64\n",
      " 37  longitude                                     21118 non-null  float64\n",
      " 38  property_type                                 10559 non-null  object \n",
      " 39  room_type                                     21118 non-null  object \n",
      " 40  accommodates                                  10559 non-null  float64\n",
      " 41  bathrooms                                     10558 non-null  float64\n",
      " 42  bathrooms_text                                10547 non-null  object \n",
      " 43  bedrooms                                      10537 non-null  float64\n",
      " 44  beds                                          10551 non-null  float64\n",
      " 45  amenities                                     10559 non-null  object \n",
      " 46  price                                         21118 non-null  float64\n",
      " 47  minimum_nights                                21118 non-null  int64  \n",
      " 48  maximum_nights                                10559 non-null  float64\n",
      " 49  minimum_minimum_nights                        10550 non-null  float64\n",
      " 50  maximum_minimum_nights                        10550 non-null  float64\n",
      " 51  minimum_maximum_nights                        10550 non-null  float64\n",
      " 52  maximum_maximum_nights                        10550 non-null  float64\n",
      " 53  minimum_nights_avg_ntm                        10559 non-null  float64\n",
      " 54  maximum_nights_avg_ntm                        10559 non-null  float64\n",
      " 55  calendar_updated                              0 non-null      float64\n",
      " 56  has_availability                              10389 non-null  object \n",
      " 57  availability_30                               10559 non-null  float64\n",
      " 58  availability_60                               10559 non-null  float64\n",
      " 59  availability_90                               10559 non-null  float64\n",
      " 60  availability_365                              21118 non-null  int64  \n",
      " 61  calendar_last_scraped                         10559 non-null  object \n",
      " 62  number_of_reviews                             21118 non-null  int64  \n",
      " 63  number_of_reviews_ltm                         21118 non-null  int64  \n",
      " 64  number_of_reviews_l30d                        10559 non-null  float64\n",
      " 65  availability_eoy                              10559 non-null  float64\n",
      " 66  number_of_reviews_ly                          10559 non-null  float64\n",
      " 67  estimated_occupancy_l365d                     10559 non-null  float64\n",
      " 68  estimated_revenue_l365d                       10559 non-null  float64\n",
      " 69  first_review                                  9411 non-null   object \n",
      " 70  last_review                                   18822 non-null  object \n",
      " 71  review_scores_rating                          9411 non-null   float64\n",
      " 72  review_scores_accuracy                        9411 non-null   float64\n",
      " 73  review_scores_cleanliness                     9411 non-null   float64\n",
      " 74  review_scores_checkin                         9411 non-null   float64\n",
      " 75  review_scores_communication                   9411 non-null   float64\n",
      " 76  review_scores_location                        9411 non-null   float64\n",
      " 77  review_scores_value                           9411 non-null   float64\n",
      " 78  license                                       11598 non-null  object \n",
      " 79  instant_bookable                              10559 non-null  object \n",
      " 80  calculated_host_listings_count                21118 non-null  int64  \n",
      " 81  calculated_host_listings_count_entire_homes   10559 non-null  float64\n",
      " 82  calculated_host_listings_count_private_rooms  10559 non-null  float64\n",
      " 83  calculated_host_listings_count_shared_rooms   10559 non-null  float64\n",
      " 84  reviews_per_month                             18822 non-null  float64\n",
      " 85  scraped_at                                    21118 non-null  object \n",
      " 86  neighbourhood_group                           0 non-null      float64\n",
      " 87  popular                                       21118 non-null  int64  \n",
      " 88  price_per_night                               21118 non-null  float64\n",
      " 89  review_intensity                              21118 non-null  float64\n",
      " 90  value_score                                   21118 non-null  float64\n",
      " 91  host_activity                                 21118 non-null  int64  \n",
      " 92  location_score                                21118 non-null  float64\n",
      "dtypes: float64(49), int64(9), object(35)\n",
      "memory usage: 15.0+ MB\n",
      "None\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\2323670257.py:12: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown\n",
      "  plt.show()\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\2323670257.py:17: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown\n",
      "  plt.show()\n",
      "C:\\Users\\DELL\\anaconda3\\Lib\\site-packages\\seaborn\\_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.\n",
      "  with pd.option_context('mode.use_inf_as_na', True):\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\2323670257.py:21: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown\n",
      "  plt.show()\n",
      "C:\\Users\\DELL\\anaconda3\\Lib\\site-packages\\seaborn\\_oldcore.py:1119: FutureWarning: use_inf_as_na option is deprecated and will be removed in a future version. Convert inf values to NaN before operating instead.\n",
      "  with pd.option_context('mode.use_inf_as_na', True):\n",
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\2323670257.py:25: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown\n",
      "  plt.show()\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "df = pd.read_csv(\"data_clean.csv\")\n",
    "\n",
    "print(df.describe())\n",
    "print(df.info())\n",
    "\n",
    "# Popular vs Non-popular distribution\n",
    "sns.countplot(x=\"popular\", data=df)\n",
    "plt.show()\n",
    "\n",
    "# Correlation heatmap\n",
    "plt.figure(figsize=(10,6))\n",
    "sns.heatmap(df.corr(numeric_only=True), annot=False)\n",
    "plt.show()\n",
    "\n",
    "# Price distribution\n",
    "sns.histplot(df[\"price\"], bins=50)\n",
    "plt.show()\n",
    "\n",
    "# Reviews distribution\n",
    "sns.histplot(df[\"number_of_reviews\"], bins=50)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "5e317c93-8250-41cf-a8e8-efd150ff5eaa",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Local\\Temp\\ipykernel_11480\\3817480981.py:14: DtypeWarning: Columns (34,78) have mixed types. Specify dtype option on import or set low_memory=False.\n",
      "  df = pd.read_csv(\"data_clean.csv\")\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      " LogisticRegression\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.96      1.00      0.98      2144\n",
      "           1       0.99      0.96      0.97      2080\n",
      "\n",
      "    accuracy                           0.98      4224\n",
      "   macro avg       0.98      0.98      0.98      4224\n",
      "weighted avg       0.98      0.98      0.98      4224\n",
      "\n",
      "\n",
      " DecisionTree\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00      2144\n",
      "           1       1.00      1.00      1.00      2080\n",
      "\n",
      "    accuracy                           1.00      4224\n",
      "   macro avg       1.00      1.00      1.00      4224\n",
      "weighted avg       1.00      1.00      1.00      4224\n",
      "\n",
      "\n",
      " RandomForest\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00      2144\n",
      "           1       1.00      1.00      1.00      2080\n",
      "\n",
      "    accuracy                           1.00      4224\n",
      "   macro avg       1.00      1.00      1.00      4224\n",
      "weighted avg       1.00      1.00      1.00      4224\n",
      "\n",
      "\n",
      " GradientBoosting\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       1.00      1.00      1.00      2144\n",
      "           1       1.00      1.00      1.00      2080\n",
      "\n",
      "    accuracy                           1.00      4224\n",
      "   macro avg       1.00      1.00      1.00      4224\n",
      "weighted avg       1.00      1.00      1.00      4224\n",
      "\n",
      "\n",
      " KNN\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.96      0.99      0.97      2144\n",
      "           1       0.98      0.96      0.97      2080\n",
      "\n",
      "    accuracy                           0.97      4224\n",
      "   macro avg       0.97      0.97      0.97      4224\n",
      "weighted avg       0.97      0.97      0.97      4224\n",
      "\n",
      "Best model saved!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import classification_report\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "\n",
    "import joblib\n",
    "\n",
    "df = pd.read_csv(\"data_clean.csv\")\n",
    "\n",
    "features = [\n",
    "    \"price\",\n",
    "    \"minimum_nights\",\n",
    "    \"availability_365\",\n",
    "    \"number_of_reviews\",\n",
    "    \"price_per_night\",\n",
    "    \"review_intensity\",\n",
    "    \"value_score\",\n",
    "    \"host_activity\"\n",
    "]\n",
    "\n",
    "X = df[features].fillna(0)\n",
    "y = df[\"popular\"]\n",
    "\n",
    "# split\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "# scaling\n",
    "scaler = StandardScaler()\n",
    "X_train = scaler.fit_transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "models = {\n",
    "    \"LogisticRegression\": LogisticRegression(),\n",
    "    \"DecisionTree\": DecisionTreeClassifier(),\n",
    "    \"RandomForest\": RandomForestClassifier(n_estimators=200),\n",
    "    \"GradientBoosting\": GradientBoostingClassifier(),\n",
    "    \"KNN\": KNeighborsClassifier()\n",
    "}\n",
    "\n",
    "best_model = None\n",
    "best_score = 0\n",
    "\n",
    "for name, model in models.items():\n",
    "    model.fit(X_train, y_train)\n",
    "    pred = model.predict(X_test)\n",
    "\n",
    "    print(\"\\n\", name)\n",
    "    print(classification_report(y_test, pred))\n",
    "\n",
    "    score = model.score(X_test, y_test)\n",
    "\n",
    "    if score > best_score:\n",
    "        best_score = score\n",
    "        best_model = model\n",
    "\n",
    "joblib.dump(best_model, \"model.pkl\")\n",
    "joblib.dump(scaler, \"scaler.pkl\")\n",
    "\n",
    "print(\"Best model saved!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "dca5201e-f802-45b4-bc4c-b30d9aad988b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-05-31 22:57:18.832 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.184 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\DELL\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-05-31 22:57:19.185 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.187 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Session state does not function when running a script without `streamlit run`\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.205 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.207 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.212 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.231 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.233 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.241 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.251 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.252 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.253 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.265 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-05-31 22:57:19.272 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import joblib\n",
    "\n",
    "model = joblib.load(\"model.pkl\")\n",
    "scaler = joblib.load(\"scaler.pkl\")\n",
    "\n",
    "st.title(\"🏠 Airbnb Popularity Prediction System\")\n",
    "\n",
    "price = st.number_input(\"Price\")\n",
    "min_nights = st.number_input(\"Minimum Nights\")\n",
    "availability = st.number_input(\"Availability (365)\")\n",
    "reviews = st.number_input(\"Number of Reviews\")\n",
    "price_per_night = st.number_input(\"Price per Night\")\n",
    "review_intensity = st.number_input(\"Review Intensity\")\n",
    "value_score = st.number_input(\"Value Score\")\n",
    "host_activity = st.number_input(\"Host Activity\")\n",
    "\n",
    "if st.button(\"Predict\"):\n",
    "    data = np.array([[price, min_nights, availability, reviews,\n",
    "                      price_per_night, review_intensity,\n",
    "                      value_score, host_activity]])\n",
    "\n",
    "    data = scaler.transform(data)\n",
    "\n",
    "    pred = model.predict(data)[0]\n",
    "    prob = model.predict_proba(data)[0][1]\n",
    "\n",
    "    if pred == 1:\n",
    "        st.success(f\"POPULAR LISTING (Confidence: {prob:.2f})\")\n",
    "    else:\n",
    "        st.error(f\"NOT POPULAR (Confidence: {prob:.2f})\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "59690864-c7a0-413c-b26d-e0dc7b972d9b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
