{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "54ce7ca5-d2c7-4d88-814c-340ec0dd2fdb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total datasets found: 238\n",
      "Scraping 1: https://data.insideairbnb.com/united-states/ny/albany/2026-02-15/data/listings.csv.gz\n",
      "Scraping 2: https://data.insideairbnb.com/united-states/ny/albany/2026-02-15/visualisations/listings.csv\n",
      "Scraping 3: https://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2025-09-11/data/listings.csv.gz\n",
      "Scraping 4: https://data.insideairbnb.com/the-netherlands/north-holland/amsterdam/2025-09-11/visualisations/listings.csv\n",
      "Scraping 5: https://data.insideairbnb.com/belgium/vlg/antwerp/2025-09-28/data/listings.csv.gz\n",
      "Scraping 6: https://data.insideairbnb.com/belgium/vlg/antwerp/2025-09-28/visualisations/listings.csv\n",
      "Scraping 7: https://data.insideairbnb.com/united-states/nc/asheville/2025-09-22/data/listings.csv.gz\n",
      "Scraping 8: https://data.insideairbnb.com/united-states/nc/asheville/2025-09-22/visualisations/listings.csv\n",
      "Scraping 9: https://data.insideairbnb.com/greece/attica/athens/2025-09-26/data/listings.csv.gz\n",
      "Scraping 10: https://data.insideairbnb.com/greece/attica/athens/2025-09-26/visualisations/listings.csv\n",
      "Scraping completed successfully!\n",
      "Dataset shape: (63768, 88)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "\n",
    "BASE_URL = \"https://insideairbnb.com/get-the-data/\"\n",
    "\n",
    "headers = {\n",
    "    \"User-Agent\": \"Mozilla/5.0\"\n",
    "}\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 1: GET ALL CSV LINKS\n",
    "# -----------------------------\n",
    "def get_csv_links():\n",
    "    response = requests.get(BASE_URL, headers=headers)\n",
    "    soup = BeautifulSoup(response.text, \"html.parser\")\n",
    "\n",
    "    links = []\n",
    "\n",
    "    for a in soup.find_all(\"a\"):\n",
    "        href = a.get(\"href\")\n",
    "        if href and \"listings.csv\" in href:\n",
    "            if href.startswith(\"http\"):\n",
    "                links.append(href)\n",
    "            else:\n",
    "                links.append(\"https://insideairbnb.com\" + href)\n",
    "\n",
    "    return links\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 2: LOAD EACH DATASET\n",
    "# -----------------------------\n",
    "def load_dataset(url):\n",
    "    try:\n",
    "        df = pd.read_csv(url)\n",
    "        df[\"source_url\"] = url\n",
    "        df[\"scraped_at\"] = pd.Timestamp.now()\n",
    "        return df\n",
    "    except Exception as e:\n",
    "        print(\"Error:\", e)\n",
    "        return None\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# MAIN SCRAPING PIPELINE\n",
    "# -----------------------------\n",
    "all_data = []\n",
    "\n",
    "links = get_csv_links()\n",
    "\n",
    "print(\"Total datasets found:\", len(links))\n",
    "\n",
    "# Limit to avoid huge dataset (you can increase later)\n",
    "for i, link in enumerate(links[:10]):\n",
    "    print(f\"Scraping {i+1}: {link}\")\n",
    "\n",
    "    df = load_dataset(link)\n",
    "\n",
    "    if df is not None:\n",
    "        all_data.append(df)\n",
    "\n",
    "    time.sleep(2)  # avoid server overload\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# MERGE ALL DATA\n",
    "# -----------------------------\n",
    "final_df = pd.concat(all_data, ignore_index=True)\n",
    "\n",
    "# -----------------------------\n",
    "# SAVE RAW DATASET\n",
    "# -----------------------------\n",
    "final_df.to_csv(\"data_raw.csv\", index=False)\n",
    "\n",
    "print(\"Scraping completed successfully!\")\n",
    "print(\"Dataset shape:\", final_df.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "169f71bc-640e-4cf6-9ec0-a53d298ef45f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
